print("=== BIODATA MAHASISWA INFORMATIKA 2026 ===")
print("Nama    : Muhammad Rusdy Rahman")
print("NIM     : 2611532012")
print("Jurusan : Informatika")
print("Kelas   : IF-B")
print("Hobi    : Membaca dan Menyanyi")
print()
print()
print()
print("       *")
print("      ***")
print("     *****")
print("    *******")
print("   *********")
print("  ***********")
print(" *************")
print("  ***********")
print("   *********")
print("    *******")
print("     *****")
print("      ***")
print("       *")