<div align="center">

**LAPORAN PRAKTIKUM**

**ALGORITMA DAN PEMROGRAMAN DATA**

**“Type data dan variable Python”**

**Disusun Oleh :**

**Muhammad Rusdy Rahman**

**2611532012**

**Dosen Pengampu:**

**Dr. Ir WAHYUDI, ST., MT.**

**Asisten Praktikum:**

**Rifky Yuliandra**

<br>

 <img src="images/logo_unand.png" width="200">

<br>

**FAKULTAS TEKNOLOGI INFORMASI**

**DEPARTEMEN INFORMATIKA**

**UNIVERSITAS ANDALAS**

**2026**

</div>

## KATA PENGANTAR

Puji beserta syukur saya panjatkan atas kehadirat Tuhan Yang Maha Esa yang telah memberikan rahmat dan berkatnya, sehingga saya dapat menyelesaikan laporan praktikum mengenai pengenalan tipe data dan variabel Python yang telah dilaksanakan sebagai pertemuan ke-2 untuk mata kuliah Praktikum Algoritma dan Pemrograman. Praktikum ini berfokus pada pembahasan jenis - jenis tipe data yang ada pada bahasa pemrograman Python.

Melalui praktikum ini, hasil yang diharapkan adalah saya dapat memahami secara langsung konsep mengenai macam - macam tipe data Python dan bisa mengindentifikasi nilai dari suatu variabel serta bisa mengelompokkan nilai variabel berdasarkan tipe datanya pada bahasa pemrograman Python.

Saya menyadari bahwa laporan praktikum ini masih memiliki banyak kekurangan. Oleh karena itu, kritik dan saran yang membangun sangat diharapkan demi perbaikan dan pengembangan di masa mendatang.

Padang, 2026

---
# BAB I
# PENDAHULUAN

## 1.1 Latar Belakang
Perkembangan zaman teknologi informasi membuat pengelola data dan pembuatan sistem semakin dibutuhkan di zaman sekarang.Bahasa pemrograman yang sering digunakan adalah Python.Python menggunakan sintaks yang sederhana.Selain itu, Python digunakan untuk membuat program sistem, pengolahan data, dan pengembangan kecerdasan buatan.Dan juga, Python merupakan bahasa pemrograman paling berkembang di zaman sekarang.Oleh karena itu, hendaknya untuk memahami dasar - dasar Python untuk menjadi dasar untuk mempelajari cara membuat program di kemuian hari.

Dasar - dasar pemrograman yang harus dipelajari adalah variabel.Variabel adalah tempat untuk menyimpan data.Setiap data yang dirancang, harus ada variabel untuk menyimpan proses dari data tersebut.Dengan adanya variabel, data yang ada di dalam program dapat disimpan dan diolah dengan mudah.

Selain itu, terdapat pula tipe data yang menjadi dasar - dasar dari pemrograman.Tipe data menunjukkan jenis data apa yang sedang kita gunakan,seperti int untuk bilangan bulat, float untuk bilangan koma, string untuk kata atau kalimat, dan bool untuk benar atau salah.

Variabel dan tipe data merupakan materi dasar yang perlu dikuasai sebelum mempelajari pemrograman lebih lanjut. Melalui praktikum ini, diharapkan kita dapat memahami cara menggunakan variabel, mengenali beberapa tipe data dasar, dan menerapkannya dalam program sederhana menggunakan Python.

## 1.2 Tujuan
1. Memahami Konsep Dasar Variabel.
2. Mengenali Jenis Tipe Data Variabel.
3. Mengimplementasikan Deklarasi dan Konversi Tipe Data.
4. Menganalisis dan Mengatasi Error

## 1.3 Manfaat
1. Penguasaan Fondasi Pemrograman
2. Peningkatan Keterampilan Praktis
3. Pencegahan Kesalahan Logika Kode

---
# BAB II
# PEMBAHASAN

## 2.1 Dasar Teori
**1. Pengenalan Bahasa Pemrograman Python**

Python adalah bahasa pemrograman
tingkat tinggi yang dirancang dengan
filosofi sederhana, mudah dibaca, dan
mudah dipelajari. Python dikembangkan
oleh Guido van Rossum dan pertama kali
dirilis pada tahun 1991. Python saat ini
menjadi salah satu bahasa pemrograman
paling populer di dunia karena fleksibilitas
dan kemampuannya digunakan dalam
berbagai bidang.

**2. Konsep Variabel dalam Python**

Variabel adalah tempat yang digunakan untuk menyimpan nilai.Di dalam bahasa pemrograman, seperti Python, variabel digunakan untuk menyimpan data yang dinginkan oleh program.Setiap variabel memiliki nama yang unik yang mengidentifikasinya.Jika ada 1 huruf yang berbeda dalam pengetikkan, maka variabel tidak dapat digunakan oleh program untuk sebagai tempat penyimpanan. Di dalam variabel tersebut, ada dapat mengakses, memodifikasi, dan menghapus nilai yang ada di dalamnya.

**3. Konsep Tipe Data dalam Python**

Tipe data adalah klasifikasi data yang menggunakan jenis nilai yang tersimpan dalam suatu variabel.Setiap bahasa pemrograman memiliki berbagai tipe data yang digunakan untuk menyimpan data dalam berbagai bentuk.Dalam Python, beberapa tipe data yang umum digunakan adalah:
 - Integer (Bilangan Bulat) : Integer adalah tipe data yang digunakan untuk menyimpan bilangan bulat.Anda dapat mendekalrasikan variabel integer dengan langsung memberikan nilai bilangan bulet ke variabel.
 - Float (Bilangan Desimal) : Float adalah tipe data yang digunakan untuk menyimpan bilangan pecahan atau desimal.Anda dapat mendeklarasikan variabel float dengan memberikan nilai desimal ke variabel atau menggunakan koma setelah bilangan bulat.
 - String (Teks) : String adalah tipe data yang digunalan untuk menyimpan teks atau huruf.Anda dapat mendeklarasikan variabel string dengan menggunakan tanda kutip tunggal (') atau ganda (").
 - Boolean (Benar/Salah) : Boolean adalah tipe data yang digunakan untuk menyimpan nilai benar(True) atau nilai salah(False).Tipe data ini sangat berguna saat menangani logika dan kondisi dalam program.

 **​4. Dynamic Typing dan Type Casting**

 Variabel dalam Python berfungsi sebagai penampung data yang dapat berubah-ubah. Python menggunakan sistem dynamic typing, di mana jenis data ditentukan secara otomatis saat nilai diberikan pada variabel.Python juga menyediakan type casting yang digunakan untuk mengubah suatu nilai dari satu tipe data ke tipe lainnya. Contohnya adalah penggunaan int(), float(), dan str(). Pemahaman mengenai type casting diperlukan agar data dapat digunakan sesuai dengan operasi yang dilakukan dan mengurangi kemungkinan terjadinya type error.

## 2.2 Kode Program

### 2.2.1 Program "Numeric_2611532012"


In [27]:
# Buat file dengan nama Numerik_2012.py
# nama variabel ditambah 4 digit terakhir NIM contoh: a_5500
#create a variable with numeric type value.
a_2012 = 100
print("The type of variable having value", a_2012, "is", type(a_2012))

#create a variable with float type value.
b_2012 = 10.2345
print("The type of variable having value", b_2012, "is", type (b_2012))

#create a variale with complex type value.
c_2012 = 10 + 3j
print("The type of variable having value", c_2012, "is", type(c_2012))


The type of variable having value 100 is <class 'int'>
The type of variable having value 10.2345 is <class 'float'>
The type of variable having value (10+3j) is <class 'complex'>


**Penjelasan :**
1. Bagian pertama yang terdiri dari baris 1 sampai 2 merupakan komentar untuk membuat program yang menentukan tipe data dari masing - masing variabel .Bagian ini tidak akan diproses oleh Python.
2. Bagian kedua yang terdiri dari baris 3 yang merupakan komentar serta baris 4 dan baris 5 berfungsi untuk membuat variabel a_2012 dengan nilai 100 dan juga menampilkan nilai serta tipe datanya.
3. Bagian ketiga yang terdiri dari baris 7 yang merupakan komentar serta baris 8 dan baris 9 berfungsi untuk membuat variabel b_2012 dengan nilai 10.2345 dan juga menampilkan nilai serta tipe datanya.
4. Bagian keempat yang terdiri dari baris 11 yang merupakan komentar serta baris 12 dan baris 13 berfungsi untuk membuat variabel c_2012 dengan nilai kompleks 10 + 3j dan juga menampilkan nilai serta tipe datanya. 

### 2.2.2 Program Driver "String_2611532012"

In [28]:
#Buat file dengan nama String_2012.py
#nama variabel ditambah 4 digit terakhir NIM contoh:Rusdy_2012
#ganti programnya dan data masing2
nama_2012 = "Rusdy"
jenis_kelamin_2012 = "Laki-laki"
alamat_2012 = """
  Batu Belah
  Kec. Kampar
  Kab. Kampar
  Prov. Riau
"""
agama_2012 = "Islam"
print("Nama saya adalah :", nama_2012)
print("Jenis kelamin saya adalah :", jenis_kelamin_2012)
print("Alamat saya adalah:", alamat_2012)
print("Agama saya adalah :", agama_2012)

Nama saya adalah : Rusdy
Jenis kelamin saya adalah : Laki-laki
Alamat saya adalah: 
  Batu Belah
  Kec. Kampar
  Kab. Kampar
  Prov. Riau

Agama saya adalah : Islam


**Penjelasan :**
1. Bagian pertama yang terdari dari baris 1 sampai baris 3 merupakan komentar untuk membuat program biodata seseorang.Bagian ini tidak akan diproses oleh Python.
2. Bagian kedua yang terdiri dari baris 4 sampai baris 5 berfungsi untuk membuat variabel nama_2012 dan jenis_kelamin_2012 yang menyimpan data nama dan jenis kelamin.
3. Bagian ketiga yang terdiri dari baris 6 sampai baris 11 berfungsi untuk membuat variabel alamat_2012 berupa string yang terdiri dari beberapa baris.
4. Bagian keempat yang terdiri dari baris 12 berfungsi untuk membuat variabel agama_2012 yang menyimpan data agama.
5. Bagian kelima yang terdiri dari baris 13 sampai baris 16 berfungsi untuk menampilkan nama, jenis kelamin, alamat, dan agama dengan menggunkan kode print().

### 2.2.3 Program Driver "Input_2611532012"

In [29]:
# Buat file dengan nama Input_2611532012.py
# Buat program untuk menghitung luas persegi panjang 
# Nama variabel ditambah 4 digit nim terakhir contoh: panjang_2012
# Program ini menggunakan fungsi input()
# Memasukkan nilai panjang dan lebar persegi panjang.
# Nilai yang dimasukkan akan dikonversi menjadi tipe data integer
panjang_2012 = input("Masukkan Nilai Panjang:")
lebar_2012 = input("Masukkan Nilai Lebar:")
luas_2012 = int(panjang_2012) * int(lebar_2012)
print("Luas :", luas_2012)

Luas : 49


**Penjelasan :**
1. Bagian pertama yang terdiri dari baris 1 sampai baris 6 merupakan komentar untuk membuat program perhitungan luas.Bagian ini tidak akan diproses oleh Python.
2. Bagian kedua yang terdiri dari baris 7 dan baris 8 berfungsi untuk menyimpan data panjang_2012 dan lebar_2012 berupa string.
3. Bagian ketiga yang terdiri dari baris 9 yang berfungsi untuk mengubah tipe data panjang_2012 dan lebar_2012 ke bentuk integer, kemudian menghitung luas_2012 dengan mengalikan panjang_2012 dan lebar_2012.
4. Bagian keempat yang terdiri dari baris 10 yang berfungsi untuk menampilkan hasil perhitungan luas_2012 ke layar.

### 2.2.4 Program Driver "Boolean_2611532012"

In [30]:
# Buat file dengan nama Boolean_2012.py
# nama variabel ditambah 4 digit terakhir NIM contoh:nilai_2012
# Deklarasi variabel dengan tipe data Boolean
is_lulus_2012 = True
is_cumlaude_2012 = True

# Menggunakan nilai Boolean dari kondisi 
nilai_2012 = 85
batas_lulus_2012 = 75

# Menentukan nilai dari boolean dari kondisi
status_kelulusan_2012 = nilai_2012 >= batas_lulus_2012 #Hasilnya akan True

print("=== Check Kelulusan ===")
print("Nilai:", nilai_2012)
print("Apakah Lulus?:", status_kelulusan_2012)
if is_lulus_2012 and is_cumlaude_2012:
    print("Selamat, Anda lulus dengan predikat Cum Laude!")


=== Check Kelulusan ===
Nilai: 85
Apakah Lulus?: True
Selamat, Anda lulus dengan predikat Cum Laude!


**Penjelasan :**
1. Bagian pertama yang terdiri dari baris 1 sampai baris 2 merupakan komentar untuk membuat progam pengecek status kelulusan berdasarkan data.Bagian ini tidak diproses oleh Python
2. Bagian kedua yang terdiri dari baris 3 yang merupakan komentar serta baris 4 dan 5 yang berfungsi untuk menyimpan variabel is_lulus_2012 dengan nilai True dan is_cumlaude dengan nilai True.
3. Bagian ketiga yang terdiri dari baris 7 yang merupakan komentar serta baris 8 dan 9 yang berfungsi untuk menyimpan nilai_2012 sama dengan 85 dan batas_lulus_2012 sama dengan 75.
4. Bagian keempat yang terdiri dari baris 11 yang merupakan komentar dan baris 12 yang befungsi untuk menentukan status_kelulusan_2012 apakah True apabila nilai_2012 lebih besar sama dengan batas_lulus_2012.
5. Bagian Kelima yang terdiri dari baris 14 sampai baris 16 yang berfungsi untuk menampilkan data dari nilai_2012 dan menampilkan True atau False dari data status_kelulusan_2012.
6. Bagian keenam yang terdiri dari baris 17 dan 18 berfungsi untuk menentukan jika is_lulus_2012 dan is_cumlaude_2012 adalah True, maka program akan menampilkan string yang terdapat pada baris 18.

### 2.2.5 Program Driver "Konstanta_2611532012"

In [31]:
# Buat file dengan nama konstanta_2611532012.py
# Program ini menggunakan konstanta untuk menghitung luas lingkaran
# nama variabel ditambah 4 digit nim terakhir contoh: jari_1234

from typing import final 
PI_2012: final = 3.14
print("pi: %f" % (PI_2012))
jari_2012 = float(input('Masukkan nilai jari-jari: '))
luas_2012 = PI_2012 * jari_2012
print("Luas lingkaran dengan jari - jari %.2f adalah %.2f" % (jari_2012, luas_2012))


pi: 3.140000
Luas lingkaran dengan jari - jari 8.00 adalah 25.12


**Penjelasan :**
1. Bagian pertama yang terdri dari baris 1 sampai 3 merupakan komentar untuk membuat program perhitungan luas lingkaran,Bagian ini tidak akan diproses oleh Python.
2. Bagian kedua yang terdiri dari baris 5 dan baris 6 untuk mengimpor nilai PI_2012 dan menentukan konstanta tetap PI_2012 sebesar 3.14.
3. Bagian ketiga yang terdiri dari baris 7 dan baris 8 berfungsi untuk menampilkan nilai PI_2012 dan meminta pengguna memasukkan nilai jari-jari lingkaran.
4. Bagian keempat yang terdiri dari baris 9 berfungsi untuk menghitung luas lingkaran menggunakan nilai PI_2012 dan jari-jari yang telah dimasukkan.
5. Bagian kelima yang terdiri dari baris 10 berfungsi untuk mmenampilkan hasil perhitungan luas lingkaran dengan format dua angka dibelakang koma.

### 2.2.6 Program Driver "tugas2_2611532012"

In [ ]:
from typing import final 
batas_lulus_2012: final = 75.0
print("=== SISTEM REGISTRASI PRATIKAN ALPRO 2026 === ")
nama_mahasiswa_2012 = input("Masukkan Nama :")
jenis_kelamin_2012 = input("Masukkan Jenis Kelamin (L/P) : ")
umur_2012 = int(input("Masukkan Umur : "))
skor_tes_awal_2012 =float(input("Masukkan Skor Tes Awal : "))
alamat_2012 ="""
Batu Belah,
Kec. Kampar,
Kab. Kampar,
Prov. Riau """
id_token_sinyal_2012 =100+3j
print( " " )
print("=== DATA PRATIKAN & HASIL PEMERIKSAAN ===")
print("Nama Mahasiswa : ", nama_mahasiswa_2012 , "|" , "Tipe :", type(nama_mahasiswa_2012))
print("Jenis Kelamin : ", jenis_kelamin_2012, "|" , "Tipe :", type(jenis_kelamin_2012))
print("Alamat Domisili :", alamat_2012,"|", "Tipe :", type(alamat_2012))
print("Umur :", umur_2012,"|", "Tipe :", type(umur_2012))
print("Skor Tes Awal :", skor_tes_awal_2012, "|", "Tipe :", type(skor_tes_awal_2012))
print("ID Token Sinyal :", id_token_sinyal_2012, "|" ,"Tipe :", type(id_token_sinyal_2012))
print( " " )
print("=== STATUS KELULUSAN PRATIKUM ===")
print("Batas Minimum Nilai :", batas_lulus_2012)
print("Dinyatakan Lulus?:", skor_tes_awal_2012 >= batas_lulus_2012, "|", "Tipe: ", type(skor_tes_awal_2012 >= batas_lulus_2012))

=== SISTEM REGISTRASI PRATIKAN ALPRO 2026 === 
 
=== DATA PRATIKAN & HASIL PEMERIKSAAN ===
Nama Mahasiswa :  Muhammad Rusdy Rahman | Tipe : <class 'str'>
Jenis Kelamin :  L | Tipe : <class 'str'>
Alamat Domisili : 
Batu Belah,
Kec. Kampar,
Kab. Kampar,
Prov. Riau  | Tipe : <class 'str'>
Umur : 18 | Tipe : <class 'int'>
Skor Tes Awal : 82.5 | Tipe : <class 'float'>
ID Token Sinyal : (100+3j) | Tipe : <class 'complex'>
 
=== STATUS KELULUSAN PRATIKUM ===
Batas Minimum Nilai : 75.0
Dinyatakan Lulus?: True | Tipe:  <class 'bool'>


**Penjelasan :**
1. Bagian pertama yang terdri dari baris 1 sampai baris 13 merupakan bagian untuk memasukkan data yang digunakan untuk registrasi mahasiswa seperti nama, jenis kelamin, umur, skor, alamat, dan ID token sinyal.Dan juga baris awal ini terdapat data final yang tidak bisa diubah yaitu nilai batas lulus = 75.0. Baris 14 menampilkan baris kosong.
2. Bagian kedua yang terdiri dari baris 15 sampai baris 21 merupakan bagian untuk menampilkan data yamg telah diinputkan pada bagian pertama, dan juga bagian ini juga menampilkan tipe data yang telah diinputkan sebelumnya pada bagian pertama.Baris 22 menampilkan baris kosong.
3. Bagian ketiga yang terdiri dari baris 23 sampai baris 25 merupakan bagian untuk menentukan status kelulusan mahasiswa.Bernilai True untuk skor diinputkan lebih besar sama dengan nilai batas lulus dan False untuk skor yang diinputkan lebih kecil dari nilai batas lulus.Bagian ini juga menampilkan tipe data dari pernyataan tersebut True atau False.

---
# BAB III
# KESIMPULAN

Berdasarkan kegiatan praktikum Algoritma dan Pemrograman yang telah dilakukan, dapat diperoleh beberapa kesimpulan sebagai berikut:

**1. Variabel dan tipe data adalah fondasi pemrograman Python.** 
Python menyediakan berbagai tipe data dasar seperti int, float, complex, str, dan bool, yang dapat diperiksa menggunakan fungsi type() untuk memastikan data disimpan dan diolah sesuai jenisnya.

**2.Python menggunakan dynamic typing dan memerlukan type casting.** 
Tipe data variabel ditentukan otomatis saat program dijalankan, dan karena fungsi input() selalu menghasilkan string dan konversi tipe data (int(), float(), str()) diperlukan agar data dapat digunakan dalam operasi perhitungan dan menghindari type error.

**3.Konsep variabel, tipe data, operator, dan konstanta dapat diterapkan untuk membuat program sederhana.** 
Di dalam praktikum ini kita berhasil mengimplementasikan program seperti membuat tipe data, membuat biodata diri, menghitung luas persegi panjang, menghitung luas lingkaran dengan konstanta, dan menentukan status kelulusan menggunakan tipe Boolean, sehingga tujuan praktikum tercapai.

---
## DAFTAR PUSTAKA

[1] Ardiansah Irfan, Ryan Hara Permana, "Memulai Belajar Python dari Nol ," [2023], hal 14 - 20

[2] Haryo Koco Buwono
, Andika Setiawan, Deby Puspitaningrum, dan Harwidyo Eko
Prasetyo
, "Jurnal Konstruksia Volume 16 Nomer 2 ," [2025], Hal 149

[3] Heru Saputra, dkk , "Strutur Data dan Algoritma dalam Python Panduan Praktis ," [2025], hal 23